# Generated by Django 4.2.4 on 2023-08-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_cliente_producto_proveedor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
