# Generated by Django 4.2.4 on 2023-08-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_delete_entregable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion',
            new_name='email',
        ),
    ]
